### PR TITLE
#298 Add French content

### PR DESCRIPTION
**Pull request by loganmzz**
Following issue #298, here's proposal to add French content.

Format & file organization are opened for discussion still PR in draft.

### CODE REVIEW

**Comment by loganmzz** [comment]
For information, I have initialized a Google Sheet in order to share with French community. Format is simple for the moment but should be enough to generate `*.ts` files.

**Comment by on3iro** [comment]
Awesome. For reference: this is what the data should eventually look like @loganmzz 
https://github.com/on3iro/aeons-end-randomizer/tree/dev/src/config/DATA/aeonsEnd

**Comment by loganmzz** [comment]
I'm close to have finished the base set. I'm still missing basic nemesis cards. I will add it tomorrow and then work on generator.

**Comment by loganmzz** [comment]
Not sure to understand how you wish handle Expansion language switch but we also need to still be able to mix French and English for different expansions.

**Comment by on3iro** [comment]
@loganmzz that's actually no issue at all. We will use english as fallback for all languages. Meaning that our internal lookup will first check, if there is an entity of the corresponding language and if not, it will simply get the english one.

**Comment by loganmzz** [comment]
Ok but that's exactly my point. French users want to choose language for each set. For example, some have bought War Eternal in English version and mix their French Core box content with English War Eternal. But War Eternal French version should be delivered in May/June.

This some will keep using French Core + English War Eternal, and others will use French Core + French War Eternal !

**Comment by on3iro** [comment]
@loganmzz ah now i see. That makes things a lot more complex - honestly I am not quite sure if I want to introduce this kind of complexity.

At this point I see two options
a) Continue the road I proposed - that would mean, you either choose language X or Y with english as fallback. That would mean there is no dynamic matching.
This would currently be my favored option
b) Introduce the language setting to each expansion. You would still structure the data almost like I described above, but we would add a language select to each expansion, so you could select which one you would like to use. That would basically even allow mixing and matching of more than two languages. Each expansion would only show the languages it has available.

The more I think about it, option **b)** would also not be that hard to implement. Its just a bit more UI clutter, but I think we could live with that.

**Comment by loganmzz** [comment]
I perfectly understand the impact, to be honest your first suggestion is a perfect match for me as I target to have only French content.

That's why my first proposal is to just add new independant set where all code are suffixed with `_VF` and add ` (VF)` in expansion title/name to distinguish them on expansion selection screen.

**Comment by on3iro** [comment]
@loganmzz the way I would like to implement the feature you would not have to distinguish the expeditions. Let me explain:

All our settings are basically a huge lookup table. So if for example I need card **X** somewhere in my code, I will get all the information by its id. This happens via composed selectors (somewhat comparable to getters in the object oriented world).
If we keep all ids the same and do not distinguish IDs (as per your proposal), we can do the following:

We will load all available languages into our lookup object.
This would look something like this:

```js
{
    eng: {
         'expansionA': { ... }
         ....
    },
    fr: {
         'expansionA': { .... }
         .....
    }
}
```

You would now select your language globally and in your case choose french.

With the code change I have in mind, the following would happen.

Our old selectors basically says something along the lines of "give me card X".

Our updated selectors will say something like "give me card X from language Y and fallback to language Z if you don't find the entity".

That way we would not have to worry about any issues with missing expansions, all settings selections would still be viable and we would not have tons of settings clutter because of additional expansions in other languages. This is a way cleaner for the UI. Of course this does mean we will have to do a bit more work to update the code accordingly, but that shouldn't be that big of a deal. :)

**Comment by loganmzz** [comment]
My purpose is that global language settings doesn't fit needs for people mixing language content. That's why quick win is to distinguish set per language. Easy to integrate, no impact on your code, only on data.

Thus, if you prefer to implement language, it's fine as long as you have per expansion language switch.

Ok, maybe I'm anticipating too much ... If per expansion language is a too big deal, for the moment, what do you think to simply ask the community about usage ? A simple poll on BGG should be fine.

As agile-perspective, I see 3 steps : 

1) Dedicated language expansion (my quick win proposal)
2) Global language switch (your proposal)
3) Per-expansion language switch (my target proposal)

What's the workload/delivery date difference between each option ?

**Comment by loganmzz** [comment]
You should have write permissions on my branch, can you add a commit as I can see language integration ?

**Comment by on3iro** [comment]
@loganmzz I would probably go directly with option 3.

Option 1. is actually not really an option, because it would mess with the users settings saved to their respective indexeddb. This will be a hell of a mess to clean up later and would make the app prone to runtime errors, as  soon as we move on to a proper implementation. Therefore I would scratch that. 

Apart from that: both option 2 + 3 don't seem too hard to build. While option 3 will certainly take a bit longer, the difference is negligible.

No matter which implementation we choose, the feature would be released with the next major version anyway, as our dev branch moved forward quite a lot and is nowhere near stable yet.

However we are planning a beta phase on a different URL for the next major release in which you could then participate to tinker with the feature a bit earlier. 

I assume that the actual AER 3.0.0 releaes will happen somewhere around late April/early Mai.
But that's just an estimation. I currently do make very good progress with the implementation of custom narrative expeditions, which is the major addition in this release.

> You should have write permissions on my branch, can you add a commit as I can see language integration ?

Sorry, I am not quite sure, what you want me to do here - can you please explain a bit more?

**Comment by loganmzz** [comment]
Just commit a dummy data structure that I can fill :)

**Comment by on3iro** [comment]
Ah - I see - don't worry about the language implementation at all :)

Just mimic the existing data and make sure that all IDs are equivalent.
I will take care of the rest as soon as I tackle the feature :+1:

**Comment by loganmzz** [comment]
Ok, so I keep using a new directory for each expansion, sibling original ones or do you prefer a specific directory for the language ?

**Comment by on3iro** [comment]
It would probably be best if you add a `FR` directory inside `src/config/` and then mimic the structure of all directories from `src/config/DATA`

**Comment by loganmzz** [comment]
I finally have been able to spend some hours to write some code to extract Google Sheet data and generate ts files. Result is there: https://github.com/loganmzz/aeons-end-randomizer-data-generator

I just have to handle special format for special cells (see README for more info):
* Mage abilities
* Card effects

**Comment by loganmzz** [comment]
Special text should have been fixed. So still mixing:
* Basic nemeses cards
* Small expansions already available in French

I have added all expansions even if there's no data, do you prefer that I only output non-empty ones ? (having at least 1 nemesis **and** 1 mage **and** 1 card)

**Comment by on3iro** [comment]
Awesome :) - it doesn't really matter, if you add empty files or not. So do whatever suites you best.

One thing - I am probably going to move the data as well as our domain types into its own module. It could very well be, that i finish doing so, before your PR is ready. If that's the case, I would simply share the link to the new repo with you, so that you can open another PR against the data repository and we will close this one :)

**Comment by on3iro** [comment]
So as I wrote before: i moved the data out ouf this repository. Could you please open another PR against this repo instead:

https://github.com/on3iro/aer-data

The directory structure hasn't really changed much, apart from moving  everything out of `config` directly into `src`.

I am closing this PR in favor of the new one :). Thanks!

**Pull request closed without merging**
