### PR TITLE
Some Past and Future fixes

### PR DESCRIPTION
**Pull request by deusabianca**
Fix Harbinger Descent's and Encased Fossil's ID, remove redundant New Age spells from PAF's cards.ts

### CODE REVIEW

**Comment by Torgen** [comment]
Inscrutable Artifact's id also has a space.

**Comment by on3iro** [comment]
@deusabianca Thanks for the fixes. Could you please also make the adjustment @Torgen suggested? Then this should be good to go :)

**Comment by deusabianca** [comment]
Done.
What I would watch for this to fix: Resonant Pearl was not appearing at all for New Age, and Harbinger Descent appearing twice for Past and Future. If it's not fixed after this I'm not sure what is causing it.
image image

**Comment by on3iro** [comment]
> Done. What I would watch for this to fix: Resonant Pearl was not appearing at all for New Age, and Harbinger Descent appearing twice for Past and Future. If it's not fixed after this I'm not sure what is causing it. image image

Alright, thanks for the headsup. I currently don't have time to check this out, but will soon.

**Comment by deusabianca** [comment]
Hi, any update?

**Comment by on3iro** [comment]
> Hi, any update?

Sorry not yet. Pretty busy right now.

**Comment by on3iro** [comment]
Finally got around to test this. Thanks @deusabianca :)

**Comment by on3iro** [comment]
I'll have to fix  e2e-tests - don't have time for that right now. So this'll have to wait a big longer (unless you can fix them yourself @deusabianca )

**Comment by on3iro** [comment]
Hey @deusabianca I haven't forgotten about his, I just didn't find time, yet. Just so you know :)

**Comment by deusabianca** [comment]
Hello, I tried to make sense of how to fix it but I have no idea honestly. Anyway I hope you're doing well.

BTW I would be more than willing to add the data for the new cards from wave 8 when that comes. But would need help for however to integrate it.

**Comment by on3iro** [comment]
> Hello, I tried to make sense of how to fix it but I have no idea honestly. Anyway I hope you're doing well.
> 
> BTW I would be more than willing to add the data for the new cards from wave 8 when that comes. But would need help for however to integrate it.

hey @deusabianca , yeah - sorry that it's taking me so long to fix this. Unfortunately I don't have any time to dedicate to this right now. It will definitely be a while until I'll be able to look into this.
Fixing these tests is a bit of a pain.

I think I'll remove that they are mandatory for merging for now, so I can make a release with your fixes. In the end it's just a content change anyway, so it shouldn't do any damage to the app itself.

Regarding wave 8: you are more than welcome to provide content. Thanks a lot for your effort. It might make sense to create an issue for this so we can assign you. That way other people know, that someone is already working on this.
Would you please be so kind and do that?
Thanks :)

**Comment by deusabianca** [comment]
Hey @on3iro, looks like this did break the supply randomizer. This should probably be reverted for now.

And sure I can create the issue regarding wave 8.

**Comment by on3iro** [comment]
> Hey @on3iro, looks like this did break the supply randomizer. This should probably be reverted for now.
> 
> And sure I can create the issue regarding wave 8.

oh, thanks for letting me know - ill revert asap

**Pull request merged**
