### PR TITLE
FEATURE: Buttons to deselect cards by keyword

### LINKED ISSUE #502: Quickly disable cards by tag
When setting up the sets and cards to use, it would be convenient to have buttons to disable all nemeses/mages/cards with certain tags. The Weak and Strong tags and the custom legacy characters are the most obvious ones, but fire and Xaxos are reasonable ones to want to exclude, so it's probably simplest and most future proof to give a quick deselect button for any tag that exists.

### PR DESCRIPTION
**Pull request by Torgen**
Fixes #502

### CODE REVIEW

**Comment by on3iro** [comment]
@Torgen This looks great, thanks for the contribution. One minor thing: could you please remove the stray `console.logs`? :) 

Maybe we could even make these toggles instead of deselectors - what do you think?

**Comment by Torgen** [comment]
I think if some of the cards were selected and some were not, toggling them all would feel weird. I'm not sure what interface would need to do that. Maybe if it required toggling them all in the same direction it could work, but (as in this case) you probably already know what direction that should be.

**Comment by on3iro** [comment]
Yeah, I would assume that it works like most (de-)select all-checkboxes:

- if all are deselected -> the toggle would select all
- if all or some are selected -> the toggle would deselect all

If you have some  cards of the respective keyword selected and don't intent to overwrite them, you would just not use the toggle at all.

**Comment by Torgen** [comment]
Also, I thought you meant the action, not the UI.
I don't know if someone who would want to deselect all of a type would ever want to select all of a type. Maybe for Xaxos? I just know the use case my friend (who essentially always uses his browser in incognito mode) has, which is setting up the supply quickly from a blank slate. For that he only cares about deselecting.
This only affects supply cards, so deselecting "Fire Token" does carry the risk that you'll get Paradox of Myth and Bone who has several guaranteed cards that add fire tokens.

**Comment by on3iro** [comment]
Alright, I am fine with that :) Would you mind removing the `console.log`s? Afterwards we can merge and release this.

**Comment by Torgen** [comment]
I force pushed with them removed, unless there are some I missed.

**Comment by Torgen** [comment]
Hmm, weird. I force pushed something.

**Pull request closed without merging**
